updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
version: 2
