updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2
