auto:
  - .github/workflows/*
  - .github/actions/*
  - .github/action.yml
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/CODEOWNERS
bug:
  - bug/*
ci:
  - ci/*
conf:
  - .*
  - '**/*.jsonc'
  - '**/*.jsonl'
  - '**/*.json5'
  - '**/*.yaml'
  - '**/*.yml'
  - '**/*.toml'
  - '**/*.ini'
  - '**/*.config.*'
  - .git*
  - .env*
  - .*rc
  - CITATION.cff
  - .editorconfig
  - tsconfig.json
  - package.json
data:
  - '**/*.json'
deps:
  - package.json
  - package-lock.json
  - npm-shrinkwrap.json
  - bun.lock
  - bun.lockb
  - yarn.lock
  - yarn.lockb
  - pnpm-lock.yaml
  - '**/*requirements*.txt'
docs:
  - LICENSE
  - '**/.md'
  - '**/*.markdown'
  - '**/*.mdx'
fix:
  - hotfix/*
  - bugfix/*
  - fix/*
func:
  - '**/*.js'
  - '**/*.cjs'
  - '**/*.mjs'
  - '**/*.ts'
  - '**/*.jsx'
  - '**/*.tsx'
  - '**/*.ejs'
  - '**/*.py'
make:
  - build/*
perf:
  - perf/*
refac:
  - refactor/*
res:
  - '**/*.avif'
  - '**/*.bmp'
  - '**/*.eps'
  - '**/*.heic'
  - '**/*.heif'
  - '**/*.ico'
  - '**/*.icns'
  - '**/*.gif'
  - '**/*.jpeg'
  - '**/*.jpg'
  - '**/*.tiff'
  - '**/*.tif'
  - '**/*.psd'
  - '**/*.ai'
  - '**/*.mov'
  - '**/*.mp4'
  - '**/*.avi'
  - '**/*.wmv'
  - '**/*.flv'
  - '**/*.mkv'
  - '**/*.webm'
  - '**/*.mpeg'
  - '**/*.mpg'
  - '**/*.png'
  - '**/*.svg'
  - '**/*.webp'
task:
  - .github/linters/*
  - .gitignore
test:
  - test/**/*
  - '**/*.test.*'
  - '**/*.spec.*'
ui:
  - '**/*.css'
  - '**/*.scss'
  - '**/*.sass'
  - '**/*.less'
  - '**/*.styl'
vers:
  - '**/*version*.*'
  - '**/*semver*.*'