'@types':
  - changed-files:
      - '**/*.d.ts'
automation:
  - changed-files:
      - .github/**/*.yml
      - .github/**/*.yaml
      - .github/**/*.json
      - .github/workflows/**
      - .github/actions/**
      - .github/workflows/*.yml
      - .github/actions/*.js
      - action.yml
      - .github/action.yml
chore:
  - changed-files:
      - .github/*
      - .gitignore
      - .eslintrc*
      - .prettier*
config:
  - changed-files:
      - .*rc
      - '**/*.{json5,json,jsonc,jsonl}'
      - '**/*.{yaml,yml}'
      - '**/*.config.*'
      - config/**/*
      - '*config*.*'
deps:
  - changed-files:
      - package.json
      - package-lock.json
      - npm-shrinkwrap.json
      - '**/*requirements*.txt'
docs:
  - changed-files:
      - '**/*.md'
functional:
  - changed-files:
      - '**/*.{cjs,js,mjs}'
media:
  - changed-files:
      - '**/*.svg'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.webp'
      - '**/*.ico'
      - '**/*.avif'
test:
  - changed-files:
      - test/**/*
      - .c8rc
      - .c8rc.*
      - '**/*.test.js'
      - '**/*.spec.js'
version:
  - changed-files:
      - src/**/*version*.js
      - src/**/*semver*.js