automation:
  changed-files:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    - '.github/**/*.json'
    - '.github/workflows/**'
    - '.github/actions/**'
    - '.github/workflows/*.yml'
    - '.github/actions/*.js'
    - 'action.yml'
    - '.github/action.yml'
blocked:
incompatible:
  changed-files:
    - 'compat/*'
    - 'src/**/*.js'
    - 'src/utils/*.js'
    - 'src/services/*.js'
review:
conflict:
bugfix:
  changed-files:
    - 'src/**/*.js'
    - 'src/utils/*.js'
    - 'src/services/*.js'
chore:
  changed-files:
    - '.github/*'
    - '.gitignore'
    - '.eslintrc*'
    - '.prettier*'
config:
  changed-files:
    - '.*'
    - '**/*.jsonl'
    - '**/*.json5'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.toml'
    - '**/*.ini'
    - '**/*.config.js'
    - '**/*.config.ts'
    - 'config/**/*'
    - '.env*'
    - '.npmrc'
    - '.nvmrc'
    - '.babelrc*'
    - 'tsconfig.json'
    - 'jest.config.*'
dependency:
  changed-files:
    - 'package.json'
    - 'package-lock.json'
    - 'npm-shrinkwrap.json'
    - 'yarn.lock'
    - 'pnpm-lock.yaml'
    - '**/*requirements*.txt'
    - 'Gemfile*'
    - 'Cargo.toml'
    - 'Cargo.lock'
    - 'go.mod'
    - 'go.sum'
documentation:
  changed-files:
    - '**/*.md'
    - '.github/*.md'
    - '.github/CHANGELOG.md'
    - '.github/CONTRIBUTING.md'
    - '.github/CODE_OF_CONDUCT.md'
    - '.github/SECURITY.md'
    - '.github/LICENSE.md'
    - '.github/CITATION.md'
    - '.github/CODEOWNERS.md'
    - 'docs/**/*.md'
duplicate:
enhancement:
good first issue:
help wanted:
invalid:
logic:
  changed-files:
    - '**/*.js'
    - 'src/**/*.js'
    - 'src/utils/*.js'
    - 'src/services/*.js'
    - 'src/**/*.ts'
    - 'src/**/*.jsx'
    - 'src/**/*.tsx'
    - 'src/**/*.mjs'
    - 'src/**/*.cjs'
inconclusive:
visual:
  changed-files:
    - '**/*.css'
    - '**/*.scss'
    - '**/*.sass'
    - '**/*.less'
    - '**/*.styl'
    - '**/*.svg'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.jpeg'
    - '**/*.gif'
    - '**/*.webp'
    - 'src/shared/**/*.png'
    - 'src/shared/**/*.jpg'
    - 'src/shared/**/*.jpeg'
    - 'src/shared/**/*.svg'
    - 'docs/assets:media/**/*'
    - 'src/demo/**/*'
wontfix:
semver:
  changed-files:
    - 'src/utils/semver.util.js'
    - 'src/**/*version*.js'
    - 'src/**/*semver*.js'
testing:
  changed-files:
    - 'test/**/*'
    - '**/*.test.js'
    - '**/*.spec.js'
    - 'jest.config.js'
    - 'mocha.opts'
performance:
