auto:
  - changed-files:
    - ".github/workflows/*"
    - ".github/actions/*"
    - ".github/action.yml"
    - ".github/dependabot.yml"
    - ".github/labeler.yml"
    - ".github/CODEOWNERS"
    - "ci/*"
conf:
  - changed-files:
    - ".*"
    - "**/*.jsonc"
    - "**/*.jsonl"
    - "**/*.json5"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.toml"
    - "**/*.ini"
    - "**/*.config.*"
    - ".git*"
    - ".env*"
    - ".*rc"
    - "CITATION.cff"
    - ".editorconfig"
    - "tsconfig.json"
    - "package.json"
data:
  - changed-files:
    - '**/*.json'
deps:
  - changed-files:
    - package.json
    - package-lock.json
    - npm-shrinkwrap.json
    - bun.lock
    - bun.lockb
    - yarn.lock
    - yarn.lockb
    - pnpm-lock.yaml
    - '**/*requirements*.txt'
docs:
  - changed-files:
    - LICENSE
    - '**/.md'
    - '**/*.markdown'
    - '**/*.mdx'
fix:
  - changed-files:
    - hotfix/*
    - bugfix/*
    - bug/*
    - fix/*
make:
  - changed-files:
    - build/*
new:
  - changed-files:
    - '**/*.js'
    - '**/*.cjs'
    - '**/*.mjs'
    - '**/*.ts'
    - '**/*.jsx'
    - '**/*.tsx'
    - '**/*.ejs'
    - '**/*.py'
perf:
  - changed-files:
    - perf/*
redo:
  - changed-files:
    - rework/*
res:
  - changed-files:
    - '**/*.avif'
    - '**/*.bmp'
    - '**/*.eps'
    - '**/*.heic'
    - '**/*.heif'
    - '**/*.ico'
    - '**/*.icns'
    - '**/*.gif'
    - '**/*.jpeg'
    - '**/*.jpg'
    - '**/*.tiff'
    - '**/*.tif'
    - '**/*.psd'
    - '**/*.ai'
    - '**/*.mov'
    - '**/*.mp4'
    - '**/*.avi'
    - '**/*.wmv'
    - '**/*.flv'
    - '**/*.mkv'
    - '**/*.webm'
    - '**/*.mpeg'
    - '**/*.mpg'
    - '**/*.png'
    - '**/*.svg'
    - '**/*.webp'
task:
  - changed-files:
    - .github/linters/*
    - .gitignore
test:
  - changed-files:
    - test/**/*
    - '**/*.test.*'
    - '**/*.spec.*'
ui:
  - changed-files:
    - '**/*.css'
    - '**/*.scss'
    - '**/*.sass'
    - '**/*.less'
    - '**/*.styl'
vers:
  - changed-files:
    - '**/*version*.*'
    - '**/*semver*.*'