default: true
ignores:
  - node_modules
  - dist
MD013:
  code_block_line_length: 200
  heading_line_length: 80
  line_length: 80
  stern: true
  tables: true
MD028: false
MD033:
  allowed_elements:
    - br
MD036: false
MD041: true
MD046:
  style: consistent
