body:
  - attributes:
      value: |
        Thanks for taking the time to fill out this bug report!\n
        Please check our documentation first:
        - [Security Policy](.github/SECURITY.md) (for security vulnerabilities)
        - [Changelog](.github/CHANGELOG.md) (to see if this has been fixed in a newer version)
    type: markdown
  - attributes:
      description: A clear and concise description of what the bug is
      label: Bug Description
      placeholder: Tell us what happened
    id: bug-description
    type: textarea
    validations:
      required: true
  - attributes:
      description: Steps to reproduce the behavior
      label: Steps To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    id: reproduction
    type: textarea
    validations:
      required: true
  - attributes:
      description: A clear and concise description of what you expected to happen
      label: Expected Behavior
      placeholder: Tell us what should have happened
    id: expected
    type: textarea
    validations:
      required: true
  - attributes:
      description: Template Version (if applicable, e.g., if forked from a specific release of the template)
      label: Version
      placeholder: e.g. 1.1.0
    id: version
    type: input
    validations:
      required: false
  - attributes:
      description: |
        Examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 20.x.x
        - **npm**: 10.x.x
      label: Environment
      value: |
        - OS:
        - Node:
        - npm:
    id: environment
    type: textarea
    validations:
      required: true
  - attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    id: terms
    type: checkboxes
description: Report a problem or unexpected behavior
labels: ["bug"]
name: Bug Report
title: "[BUG]: "