body:
  - attributes:
      value: |
        Thank you for taking the time to help us improve our documentation!
    type: markdown
  - attributes:
      description: What type of documentation are you suggesting improvements for?
      label: Documentation Type
      options:
        - README
        - Code comments
        - API documentation
        - Usage examples
        - Tutorials
        - Website content
        - Other
    id: doc_type
    type: dropdown
    validations:
      required: true
  - attributes:
      description: Where is the documentation you're referring to? (URL, file path, etc.)
      label: Location
      placeholder: e.g., README.md, docs/usage.md, website URL
    id: location
    type: input
    validations:
      required: true
  - attributes:
      description: What is the current documentation content that needs improvement?
      label: Current Content
      placeholder: Copy and paste the relevant section or describe what exists currently...
    id: current_content
    type: textarea
    validations:
      required: false
  - attributes:
      description: What changes would you like to see in the documentation?
      label: Suggested Improvement
      placeholder: Describe your suggestion or provide the exact wording you'd like to see...
    id: suggestion
    type: textarea
    validations:
      required: true
  - attributes:
      description: Add any other context or screenshots about your suggestion here.
      label: Additional Context
      placeholder: Any additional information that would help us understand your suggestion...
    id: additional_context
    type: textarea
    validations:
      required: false
  - attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    id: terms
    type: checkboxes
description: Suggest improvements to our documentation
labels: ["docs"]
name: 📚 Documentation Improvement
title: '📚 Documentation: '