body:
  - attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Please check our documentation first:
        - [Contributing Guidelines](.github/CONTRIBUTING.md)
        - [Code of Conduct](.github/CODE_OF_CONDUCT.md)
        - [Changelog](.github/CHANGELOG.md)
    type: markdown
  - attributes:
      description: A clear and concise description of what you want to happen
      label: Feature Description
      placeholder: I would like to see...
    id: feature-description
    type: textarea
    validations:
      required: true
  - attributes:
      description: A clear and concise description of any alternative solutions or features you've considered
      label: Alternatives Considered
      placeholder: I've considered...
    id: alternatives
    type: textarea
  - attributes:
      description: Add any other context or screenshots about the feature request here
      label: Additional Context
      placeholder: Other relevant information...
    id: context
    type: textarea
  - attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    id: terms
    type: checkboxes
description: Propose a new feature or enhancement
labels: ["new"]
name: Feature Request
title: "[feat]: "