body:
  - attributes:
      value: |
        Thank you for taking the time to report a performance issue!
    type: markdown
  - attributes:
      description: Please provide a clear and concise description of the performance issue
      label: Description
      placeholder: Describe what operation is slow and how it impacts usage...
    id: description
    type: textarea
    validations:
      required: true
  - attributes:
      description: How can we reproduce this performance issue?
      label: Steps to Reproduce
      value: |
        1.
        2.
        3.
        4.
    id: reproduction
    type: textarea
    validations:
      required: true
  - attributes:
      description: What performance would you consider reasonable for this operation?
      label: Expected Performance
      placeholder: e.g., The operation should complete in under 1 second for files of this size...
    id: expected
    type: textarea
    validations:
      required: true
  - attributes:
      description: What performance are you currently experiencing?
      label: Actual Performance
      placeholder: e.g., The operation takes 15-20 seconds to complete...
    id: actual
    type: textarea
    validations:
      required: true
  - attributes:
      description: Which version of the project are you using?
      label: Version
      placeholder: e.g., 1.0.0
    id: version
    type: input
    validations:
      required: true
  - attributes:
      description: 'Please share details about your environment:'
      label: Environment
      value: |
        - Node.js version:
        - Operating System and version:
        - CPU model:
        - RAM:
        - Any other relevant hardware/software information:
    id: environment
    type: textarea
    validations:
      required: true
  - attributes:
      description: If available, include any profiling data or metrics you've collected
      label: Profiling Data
      placeholder: Paste any performance profiling data, benchmark results, or metrics here...
    id: profiling
    type: textarea
    validations:
      required: false
  - attributes:
      description: Add any other context about the problem here
      label: Additional Context
      placeholder: Any additional information that might be helpful...
    id: additional_context
    type: textarea
    validations:
      required: false
  - attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    id: terms
    type: checkboxes
description: Report a performance problem or bottleneck
labels: ["performance"]
name: ⚡ Performance Issue
title: '⚡ Performance: '