body:
  - attributes:
      value: |
        Thanks for your interest in our project! Please make sure you've checked the documentation and existing issues before submitting a question.
    type: markdown
  - attributes:
      description: What would you like to know about this project?
      label: Question
      placeholder: Ask your question here, providing as much context as possible...
    id: question
    type: textarea
    validations:
      required: true
  - attributes:
      description: Template Version (if applicable, e.g., if your question is about a specific state of the template)
      label: Version
      placeholder: e.g., 1.0.0
    id: version
    type: input
    validations:
      required: false
  - attributes:
      description: 'Please share your environment details (if relevant):'
      label: Environment
      value: |
        - Node.js version:
        - Operating System:
        - Package manager (npm/yarn/pnpm) and version:
        - Any other relevant environment information:
    id: environment
    type: textarea
    validations:
      required: false
  - attributes:
      description: Add any other context, screenshots, or code examples that might help us answer your question.
      label: Additional Context
      placeholder: Any additional details that would help us understand your question better...
    id: additional_context
    type: textarea
    validations:
      required: false
  - attributes:
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have searched the existing issues and confirmed this question hasn't been asked before
          required: true
    id: terms
    type: checkboxes
description: Ask a question about this project
labels: ["ask", "help"]
name: Question
title: "Question: ${{ github.event.issue.title }}"