description: Sets up Node.js, installs dependencies, and caches them.
inputs:
  cache:
    default: npm
    description: Cache npm dependencies.
    required: false
  node-version-file:
    default: .nvmrc
    description: Path to the .nvmrc file.
    required: false
name: Setup Node.js Environment
runs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Align Node.js version
      run: |
        # Install NVM
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
        # Use NVM to install Node.js and npm
        nvm install $(cat .nvmrc) --latest-npm
        nvm use $(cat .nvmrc)
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: ${{ inputs.cache }}
        node-version-file: ${{ inputs.node-version-file }}
    - name: Install dependencies
      run: npm ci
      shell: bash
  using: composite
