description: Sets up Node.js, installs dependencies, and caches them.
inputs:
  cache:
    default: npm
    description: Cache npm dependencies.
    required: false
  node-version-file:
    default: .nvmrc
    description: Path to the .nvmrc file.
    required: false
name: Setup Node.js Environment
runs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Align Node.js version
      run: nvm install $(cat ${{ inputs.node-version-file }}) --latest-npm && nvm use $(cat ${{ inputs.node-version-file }})
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: ${{ inputs.cache }}
        node-version-file: ${{ inputs.node-version-file }}
    - name: Install dependencies
      run: npm ci
      shell: bash
  using: composite
