name: Code Quality
'on': [pull_request]

jobs:
  code-quality:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: npm ci
      - name: Format project source code
        run: npm run format
      - name: Check-in formatting change(s) to project
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --staged --quiet || (git commit -m "Automated formatting" && git push)
      - name: Lint project source code
        run: npm run lint
      - name: Check-in linting change(s) to project
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --staged --quiet || (git commit -m "Automated linting fixes" && git push)
      - name: Check for persistent Biome issues
        id: check_biome
        run: npx biome lint src --config-path .github/configs/biome.json
        continue-on-error: true
      - name: Add 'action needed' label
        if: steps.check_biome.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['action needed']
            });
