jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Node Env and Install Dependencies
        uses: ./.github/actions/setup-node-env
      - env:
          FROM_COMMIT: ${{ github.event.before }}
          TO_COMMIT: ${{ github.sha }}
        name: Lint Commits
        run: npm run lint:commit
name: Commit Linter
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true