jobs:
  dependabot_auto_merge:
    concurrency:
      cancel-in-progress: true
      group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - id: check_run_wait
        name: Wait for status checks
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          allowed-conclusions: success,skipped # Consider skipped checks as success for auto-merge
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: Dependabot auto-merge # Avoid waiting on itself
          wait-interval: 30 # seconds
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_run_wait.outputs.conclusion == 'success'
        name: Auto-merge Dependabot PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_run_wait.outputs.conclusion != 'success'
        name: Handle merge failure (assign and label)
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "@dylarcher"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "action needed"
name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
permissions:
  contents: write # Required to merge PRs
  issues: write # Required to assign users and add labels
  pull-requests: write
