jobs:
  summarize:
    permissions:
      contents: read
      issues: write
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: inference
        name: Generate concise AI summary
        uses: actions/ai-inference@d645f067d89ee1d5d736a5990e327e504d1c5a4a # v1
        with:
          prompt: |
            Summarize the following GitHub issue clearly and concisely in one paragraph:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        name: Add summary comment to issue
        run: |
          gh issue comment $ISSUE_NUMBER --body '### 📝 AI Summary\n\n${{ steps.inference.outputs.response }}'
name: Summarize new issues using AI
'on':
  issues:
    types: [opened]
