jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          submodules: true
      - name: Apply project labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          configuration-path: .github/labeler.yml
          dot: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
name: Apply labels to PRs and issues
'on': [issues, pull_request_target]