jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@dcd7002c2b353f8e53fdd460ba018a180369ac25 # v4
      - name: Apply project labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: .github/labeler.yml
          dot: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
name: Apply labels to PRs and issues
'on': [issues, pull_request_target]