name: PR Automation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  automate_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write # Needed for assigning issues/PRs and adding to projects
      contents: read # Needed to read repo content, like branch name or files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply Branch Prefix Label
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          LABEL_TO_ADD=""
          if [[ "$BRANCH_NAME" == feat/* ]]; then
            LABEL_TO_ADD="feature"
          elif [[ "$BRANCH_NAME" == fix/* ]]; then
            LABEL_TO_ADD="bugfix"
          elif [[ "$BRANCH_NAME" == chore/* ]]; then
            LABEL_TO_ADD="chore"
          elif [[ "$BRANCH_NAME" == docs/* ]]; then
            LABEL_TO_ADD="documentation"
          elif [[ "$BRANCH_NAME" == ci/* ]]; then
            LABEL_TO_ADD="ci"
          elif [[ "$BRANCH_NAME" == refactor/* ]]; then
            LABEL_TO_ADD="refactor"
          elif [[ "$BRANCH_NAME" == test/* ]]; then
            LABEL_TO_ADD="testing"
          elif [[ "$BRANCH_NAME" == perf/* ]]; then
            LABEL_TO_ADD="performance"
          elif [[ "$BRANCH_NAME" == style/* ]]; then
            LABEL_TO_ADD="style"
          elif [[ "$BRANCH_NAME" == build/* ]]; then
            LABEL_TO_ADD="build"
          fi

          if [ -n "$LABEL_TO_ADD" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL_TO_ADD"
            echo "Label '$LABEL_TO_ADD' added."
          else
            echo "No matching branch prefix found for labeling."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply File-based Labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml # Explicitly point to the config file
          sync-labels: true # Ensures labels are removed if files change and no longer match

      - name: Assign PR to @dylarcher
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee "@dylarcher"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.action == 'opened'

      - name: Request Review from Copilot
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "copilot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.action == 'opened'

      - name: Assign PR to Project
        uses: srggrs/assign-one-project-github-action@1.3.0
        # This action attempts to find a project matching PROJECT_NAME
        # If it finds one, it assigns the PR/issue.
        # If it finds multiple, it usually picks the first one.
        # If it finds none, it will likely fail or do nothing.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          PROJECT_OWNER: ${{ github.repository_owner }}
        # Adding a condition to ensure it only runs on PR open/reopen for this specific task.
        # Other event types for PRs like 'synchronize' might not be appropriate for project assignment
        # if it's already assigned.
        if: github.event.action == 'opened' || github.event.action == 'reopened'

      # Steps from the plan will be added here in subsequent tasks
