
jobs:
  automate_pr:
    permissions:
      contents: read # Needed to read repo content, like branch name or files
      issues: write # Needed for assigning issues/PRs and adding to projects
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Apply Branch Prefix Label
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          LABEL_TO_ADD=""
          if [[ "$BRANCH_NAME" == feat/* ]]; then
            LABEL_TO_ADD="new"
          elif [[ "$BRANCH_NAME" == fix/* ]]; then
            LABEL_TO_ADD="fix"
          elif [[ "$BRANCH_NAME" == chore/* ]]; then
            LABEL_TO_ADD="task"
          elif [[ "$BRANCH_NAME" == docs/* ]]; then
            LABEL_TO_ADD="docs"
          elif [[ "$BRANCH_NAME" == ci/* ]]; then
            LABEL_TO_ADD="auto"
          elif [[ "$BRANCH_NAME" == rework/* ]]; then
            LABEL_TO_ADD="redo"
          elif [[ "$BRANCH_NAME" == test/* ]]; then
            LABEL_TO_ADD="test"
          elif [[ "$BRANCH_NAME" == perf/* ]]; then
            LABEL_TO_ADD="perf"
          elif [[ "$BRANCH_NAME" == css/* ]]; then
            LABEL_TO_ADD="ui"
          elif [[ "$BRANCH_NAME" == build/* ]]; then
            LABEL_TO_ADD="make"
          fi
          if [ -n "$LABEL_TO_ADD" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL_TO_ADD"
            echo "Label '$LABEL_TO_ADD' added."
          else
            echo "No matching branch prefix found for labeling."
          fi
      - name: Apply File-based Labels
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        name: Assign PR to @dylarcher
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee "@dylarcher"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        name: Request Review from Copilot
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "copilot"
      - continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          PROJECT_OWNER: ${{ github.repository_owner }}
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        # This action attempts to find a project matching PROJECT_NAME
        # If it finds one, it assigns the PR/issue.
        # If it finds multiple, it usually picks the first one.
        # If it finds none, it will likely fail or do nothing.
        name: Assign PR to Project        # Adding a condition to ensure it only runs on PR open/reopen for this specific task.
        # Other event types for PRs like 'synchronize' might not be appropriate for project assignment
        # if it's already assigned.
        uses: srggrs/assign-one-project-github-action@1.3.0
name: PR Automation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
