jobs:
  build-and-release:
    name: Build and Release
    permissions:
      contents: write # To create releases and upload assets
      pull-requests: read # Optional: if you want to link PRs in release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for release note generation
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc # Read version from .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Run build script
        run: npm run build
      - id: get_version
        name: Get version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Create release directory
        run: mkdir -p release
      - name: Package release artifacts
        run: |
          zip -r release/release-${{ steps.get_version.outputs.VERSION }}.zip dist README.md LICENSE package.json
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/release-${{ steps.get_version.outputs.VERSION }}.zip
          generateReleaseNotes: true # Automatically generate release notes
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
name: Create Release
on:
  push:
    tags:
      - v*.*.* # Trigger on version tags like v1.0.0, v0.1.0
