jobs:
  update_template:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4
        with:
          fetch-depth: 0
      - name: Setup Node Env and Install Dependencies
        uses: ./.github/actions/setup-node-env
      - name: Update from template repository
        run: npm run update:starter-files
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if there are any changes to commit
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          git add .
          git commit -m "chore: update from starter template"
          # Pull before pushing to avoid conflicts if the branch was updated since checkout
          git pull --rebase
          git push
name: Update from Template
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # For scheduled runs, ref is the default branch
  cancel-in-progress: true
on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: 0 0 * * * # Runs daily at midnight UTC
