jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Node Env and Install Dependencies
        uses: ./.github/actions/setup-node-env
      - id: changelog_script
        name: Generate changelog
        run: node build/generate-changelog.js
      - env:
          NEW_VERSION: ${{ steps.changelog_script.outputs.new_version }}
        name: Commit and Push Changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if CHANGELOG.md has changes
          if git diff --quiet CHANGELOG.md; then
            echo "No changes to CHANGELOG.md, skipping commit."
          else
            echo "CHANGELOG.md updated, committing and pushing."
            git add CHANGELOG.md
            # Use the NEW_VERSION env var in the commit message
            git commit -m "docs: Update CHANGELOG.md for version ${NEW_VERSION}"
            git push
          fi
name: Update Changelog
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
permissions:
  contents: write
