---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  lint_and_fix:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: |
          yamllint --config-file .github/linters/.yamllintrc .
      - id: check_changes
        name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_changes.outputs.has_changes == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Create PR for Main Branch Fixes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          BRANCH_NAME="yamllint-fixes-${{ github.run_id }}"
          echo "Creating branch $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Automated YAML linting fixes"
          echo "Pushing branch $BRANCH_NAME"
          git push --set-upstream origin $BRANCH_NAME
          echo "Creating Pull Request"
          gh pr create \
            --title "Automated YAML Linting Fixes" \
            --body "Yamllint found and fixed linting issues. Please review and merge." \
            --label "action needed" \
            --base main \
            --head $BRANCH_NAME
name: YAML Lint and Fix
'on':
  push:
    branches:
      - main